// Home page
export const ADD_HOME_PAGE_ART = 'ADD_HOME_PAGE_ART';
export const CLEAR_ART_LIST = 'CLEAR_ART_LIST';
export const SET_LAST_ART = 'SET_LAST_ART';
export const SET_ERROR_HOME = 'SET_ERROR_HOME';
export const SET_IS_LOADING_HOME = 'SET_IS_LOADING_HOME';

// Artist page
export const SET_ARTIST_LIST = 'SET_ARTIST_LIST';
export const SET_ERROR_ARTIST_PAGE = 'SET_ERROR_ARTIST_PAGE';

// Artist Profile page
export const SET_ARTIST_PROFILE = 'SET_ARTIST_PROFILE';
export const SET_ARTIST_ARTLIST = 'SET_ARTIST_ARTLIST';
export const CLEAR_ARTIST_ART_LIST = 'CLEAR_ARTIST_ART_LIST';
export const SET_ERROR_ARTIST_PROFILE = 'SET_ERROR_ARTIST_PROFILE';
export const SET_ARTIST_LAST_ART = 'SET_ARTIST_LAST_ART';
